-- TABLAS EN ESPANOl (Solicitado por Usuario)

-- 1. Clientes
create table public.clientes (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  notes text,
  last_visit date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Finanzas (Antes Transactions)
create table public.finanzas (
  id bigint generated by default as identity primary key,
  date date not null,
  category text not null, -- 'IPC', 'Nóminas', 'Compra Productos', 'Trimestre', 'Cobros Booksy'
  amount numeric not null,
  type text not null, -- 'income' or 'expense'
  description text,
  client_id bigint references public.clientes(id) on delete set null,
  import_id bigint, -- Optional link to original import
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Productos
create table public.productos (
  id bigint generated by default as identity primary key,
  title text not null,
  notes text,
  label_id bigint, -- Link to labels if needed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Etiquetas (Labels)
create table public.etiquetas (
  id bigint generated by default as identity primary key,
  name text not null,
  color text not null,
  position int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.clientes enable row level security;
alter table public.finanzas enable row level security;
alter table public.productos enable row level security;
alter table public.etiquetas enable row level security;

create policy "Access All Clientes" on public.clientes for all using (true) with check (true);
create policy "Access All Finanzas" on public.finanzas for all using (true) with check (true);
create policy "Access All Productos" on public.productos for all using (true) with check (true);
create policy "Access All Etiquetas" on public.etiquetas for all using (true) with check (true);
