-- 1. Clients
create table public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  notes text,
  last_visit date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Import Logs
create table public.import_logs (
  id bigint generated by default as identity primary key,
  source text not null,
  filename text,
  record_count int default 0,
  imported_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Transactions
create table public.transactions (
  id bigint generated by default as identity primary key,
  date date not null,
  category text not null, -- 'Cobros Booksy', 'Nóminas', 'IPC', 'Compras', etc.
  amount numeric not null,
  type text not null, -- 'income' or 'expense'
  description text,
  client_id bigint references public.clients(id) on delete set null,
  import_id bigint references public.import_logs(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Gift Cards
create table public.gift_cards (
  id bigint generated by default as identity primary key,
  code text not null unique,
  balance numeric not null,
  initial_amount numeric not null,
  client text not null,
  status text not null default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Product Labels (Dynamic Columns/Statuses)
create table public.product_labels (
  id bigint generated by default as identity primary key,
  name text not null,
  color text not null, -- e.g., 'bg-red-500' or '#FF0000'
  position int default 0, -- For sorting columns
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Products
create table public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  notes text,
  label_id bigint references public.product_labels(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Appointments & Calendar
create table public.appointments (
  id bigint generated by default as identity primary key,
  client text not null, -- Can link to clients table optionally, keeping text for flexibility
  date date not null,
  time text not null,
  type text not null, -- Service type
  price numeric default 0, -- Estimated earnings
  status text default 'confirmed', -- confirmed, cancelled, completed
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Daily Notes (Calendar Details)
create table public.daily_notes (
  date date primary key, -- One note per day
  content text,
  estimated_revenue numeric default 0, -- Optional cache/override
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Open for MVP)
alter table public.clients enable row level security;
alter table public.import_logs enable row level security;
alter table public.transactions enable row level security;
alter table public.gift_cards enable row level security;
alter table public.product_labels enable row level security;
alter table public.products enable row level security;
alter table public.appointments enable row level security;
alter table public.daily_notes enable row level security;

create policy "Access All" on public.clients for all using (true) with check (true);
create policy "Access All" on public.import_logs for all using (true) with check (true);
create policy "Access All" on public.transactions for all using (true) with check (true);
create policy "Access All" on public.gift_cards for all using (true) with check (true);
create policy "Access All" on public.product_labels for all using (true) with check (true);
create policy "Access All" on public.products for all using (true) with check (true);
create policy "Access All" on public.appointments for all using (true) with check (true);
create policy "Access All" on public.daily_notes for all using (true) with check (true);
